repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --remove-duplicate-keys,
            --remove-unused-variables,
          ]

      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=100]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            --disable=missing-module-docstring,
            --disable=missing-class-docstring,
            --disable=missing-function-docstring,
            --disable=C0103,
            --disable=C0411,
            --disable=R0903,
            --disable=R0901,
            --disable=E1101,
            --disable=W0718,
            --ignored-modules=migrations,
          ]
