# Generated by Django 4.1.7 on 2023-03-31 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company_back", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="initiator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="reciever",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reciever",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company_back.chat"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="gift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company_back.gift"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="balance",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company_back.balance",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="gift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company_back.gift"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="reciever",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company_back.media",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company_back.balance",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company_back.country",
            ),
        ),
    ]
