# Generated by Django 4.1.7 on 2023-03-31 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company_back", "0002_alter_chat_user1_alter_chat_user2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="gift",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company_back.gift",
            ),
        ),
    ]
