# Generated by Django 4.1.7 on 2023-03-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_back", "0003_alter_match_date_alter_message_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="date",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
