# Generated by Django 4.1.7 on 2023-05-04 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_back', '0005_alter_purchase_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_back.gift'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
