# Generated by Django 4.2.1 on 2023-05-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_back', '0006_alter_purchase_gift_alter_purchase_reciever'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='image',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='message',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
