# Generated by Django 4.1.7 on 2023-03-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urt', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstNmae', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=32)),
                ('birthDate', models.DateField()),
                ('timezone', models.IntegerField(blank=True, default=0)),
                ('avatarId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='models.media')),
                ('balanceId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='models.balance')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.country')),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
                ('balanceId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.balance')),
                ('giftid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.gift')),
                ('reciverId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.user')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=16)),
                ('chatId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.chat')),
                ('giftId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.gift')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.user')),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
                ('initiatorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initiator', to='models.user')),
                ('reciverId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reciver', to='models.user')),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='imageId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='models.media'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user1Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to='models.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to='models.user'),
        ),
    ]
